<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tex</string>
		<string>ltx</string>
	</array>
	<key>name</key>
	<string>LaTeXing</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>%\s*-\*-\s*(?:root|pdf)\s*:\s*(.+)-\*-</string>
			<key>name</key>
			<string>comment.line.percentage.latexing</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%).*$\n?</string>
			<key>name</key>
			<string>comment.line.percentage.tex meta.no-spellcheck</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\)(?:subfile))(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.include.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>support.class.latex</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.include.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\)(?:bibliography))(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bibliography.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>support.class.latex</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.bibliography.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\)(?:bibentry))(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bibentry.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>support.class.latex</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.citation.bibentry</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((\\)(?:hyperref))(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.hyperref.latex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>support.class.latex</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.citation.hyperref</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.ing</string>
	<key>uuid</key>
	<string>2227a33d-299e-4aff-b493-4f9d2375f5ad</string>
</dict>
</plist>
