<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rnw</string>
		<string>snw</string>
		<string>rtex</string>
	</array>
	<key>name</key>
	<string>LaTeXing (Knitr)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.tex.latex.knitr</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.knitr.ing</string>
	<key>uuid</key>
	<string>2227a33d-299e-4aff-b493-4f9d2375f5ad</string>
</dict>
</plist>
