<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fig</string>
		<string>tikz</string>
	</array>
	<key>name</key>
	<string>LaTeXing (TikZ)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.tex.latex.tikz</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.tikz.ing</string>
	<key>uuid</key>
	<string>076d0b93-e355-41f2-925a-e9c140144693</string>
</dict>
</plist>
